version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: tododb
      TZ: UTC
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
